OrLog/Controllers/StalkController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace OrLog.Controllers
{
    [Route("/")]
    public class StalkController : Controller
    {
        // GET: Stalk
        [HttpGet]
        public async Task<ActionResult> Index([FromQuery]string channel, [FromQuery]string nick)
        {
            ViewBag.channel = channel;
            ViewBag.nick = nick;
            var monthsurl = $"https://overrustlelogs.net/api/v1/{channel}/months.json";
            ViewBag.url = monthsurl;
            var latesturl = $"https://overrustlelogs.net/{channel} chatlog/current/{nick}.txt";

            if (string.IsNullOrWhiteSpace(channel) || string.IsNullOrWhiteSpace(nick))
            {
                return View();
            }
            try
            {
                var logcontent = await GetString(latesturl);
                if (logcontent == null || !logcontent.StartsWith("["))
                {
                    Console.WriteLine($"Couldn't get {nick} for channel {channel}");
                    ViewBag.Error = $"Couldn't get {nick} for channel {channel}";
                    return View();
                }
                var d = logcontent.Substring(1, 23).Replace("UTC", "-0000");
                
                var date = DateTime.Parse(d);
                ViewBag.latest = logcontent;

                var monthcontent = await GetString(monthsurl);
                if (monthcontent == null)
                {
                    ViewBag.Error = $"Failed getting months for {channel}";
                    return View();
                }
                var months = JsonConvert.DeserializeObject<List<string>>(monthcontent);

                ViewBag.latestmonth = date.ToString("MMMM yyyy");
                var newmonths = new List<string>();
                months.ForEach(m =>
                {
                    var mo = DateTime.Parse(m);

                    if (mo < date && mo.ToString("Y") != date.ToString("Y"))
                    {
                        newmonths.Add(m);
                    }
                });
                ViewBag.months = newmonths;
                return View();
            }
            catch(Exception)
            {
                HttpContext.Response.StatusCode = 404;
                return View();
            }
        }

        private async Task<string> GetString(string url)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.Timeout = TimeSpan.FromSeconds(10);
                    var log = await client.GetAsync(url);
                    if (log.IsSuccessStatusCode)
                    {
                        return await log.Content.ReadAsStringAsync();
                    }
                    HttpContext.Response.StatusCode = 404;
                    return null;
                }
            }
            catch (Exception)
            {
                HttpContext.Response.StatusCode = 404;
                return null;
            }
        }
    }
}

OrLog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OverRustle Logs</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" href="~/css/orl.css" asp-append-version="true" />
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico">
</head>
<body>
<div class="navbar-fixed" id="top">
    <nav>
        <div class="row">
            <div class="col m1 l2 hide-on-med-and-down"></div>
            <div class="nav-wrapper col s12 m10 l8">
                <span><a a class="brand-logo" href="//overrustlelogs.net/">OverRustle Logs</a></span>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a class="active deep-orange donate" href="https://www.patreon.com/overrustlelogs" target="_blank">Become a Patron!</a></li>
                    <li><a class="active" asp-controller="Stalk" asp-action="Index">Stalk</a></li>
                    <li><a class="active" href="//overrustlelogs.net/changelog">Changelog</a></li>
                    <li><a class="active" href="//overrustlelogs.net/contact">Contact</a></li>
                    <li>
                        <a style="width: 97px;" class="donate deep-orange" target="_blank" href="//twitch.streamlabs.com/overrustlelogs">
                            <i class="fa fa-paypal fa-fw"></i><span>Donate</span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col m1 l2 hide-on-med-and-down"></div>
        </div>
    </nav>
</div>
<div class="center-align" style="margin-top: 10px;">
    <a href="https://hobanco.com/orl" target="_blank">
        <img class="responsive-img" src="~/img/hobanco.jpg" style="max-height: 150px" ></img>
    </a>
</div>
@RenderBody()
<script src="//code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script src="//use.fontawesome.com/5fd85f0c6d.js"></script>
<script src="~/js/orl.js" asp-append-version="true"></script>
</body>
</html>

OrLog/Views/Stalk/Index.cshtml
@{
    ViewData["Title"] = "Stalk";
}
@{
    var channel = ViewBag.channel;
    var nick = ViewBag.nick + ".txt";
    var months = ViewBag.months;
    var latest = ViewBag.latestmonth;
    var valid = !string.IsNullOrWhiteSpace(channel) && !string.IsNullOrWhiteSpace(nick) && months != null;
}
<script >
    function appendChunk(month, id, nick, channel) {
        const link = `https://overrustlelogs.net/${channel} chatlog/${month}/userlogs/${nick}`;
        var req = new XMLHttpRequest();
        req.open("GET", link, true);
        req.setRequestHeader("Content-Type", "text/plain;charset=UTF-8");
        $(`.progressbar${id}`).show();
        req.onload = function () {
            const text = req.responseText;
            $(`.progressbar${id}`).hide();
            $(`.field${id}`).empty();
            $("<span />").text(text).appendTo(`.field${id}`);
        };
        req.send();
    }
</script>

<div class="row">
    <div class="col m1 l2 hide-on-med-and-down">
        @if (valid)
        {
            <ul class="section table-of-contents pinned-top">
                <li><a href="#top">@latest</a></li>
                @for (int i = 0; i < months.Count; i++)
                {
                    if (i == 8)
                    {
                        <li><a href="#moremonths">More Months</a></li>
                        break;
                    }
                    var s = "month" + i;
                    <li><a href="#@s">@months[i]</a></li>
                }
            </ul>
        }
    </div>
    <div class="col s12 m12 l8 hide-on-large-only center-align">
        @*stuff*@
    </div>
    <div class="col s12 m12 l8">
        <br/>
        <div class="row">
            <form method="get">
                <div class="row">
                    <div class="input-field col s5">
                        <input name="channel" type="text" value="@channel">
                        <label for="channel">Channel</label>
                    </div>
                    <div class="input-field col s5">
                        <input name="nick" type="text" value="@ViewBag.nick">
                        <label for="nick">Nick</label>
                    </div>
                    <div class="input-field col s1">
                        <button class="btn deep-orange" type="submit">
                            Stalk
                        </button>
                    </div>
                </div>
            </form>
            @if (!string.IsNullOrWhiteSpace(ViewBag.Error))
            {
                <h6>@ViewBag.Error</h6>
            }
            @if (valid)
            {
                <div class="section scrollspy" id="top">
                    <h5>@latest <span></span></h5>
                    <div class="latest text">
                        <span>@ViewBag.latest</span>
                    </div>
                </div>
                <div class="divider" style="opacity: 0.6"></div>

                for (var i = 0; i < months.Count; i++)
                {
                    if (i > 7)
                    {
                        break;
                    }
                    var c = ".field" + i;
                    var b = "btn" + i;
                    var p = ".progressbar" + i;
                    var s = ".month" + i;
                    <div class="section scrollspy" id="@s.Replace(".", string.Empty)">
                        <h5>@months[i] <span><button class="waves-effect waves-orange btn-flat @b" onclick="appendChunk('@months[i]', @i, '@nick', '@channel')">Load</button></span></h5>
                        <div class="@c.Replace(".", string.Empty) text"></div>
                        <div class="progress deep-orange @p.Replace(".", string.Empty)" style="display: none">
                            <div class="indeterminate orange"></div>
                        </div>
                    </div>
                    <div class="divider" style="opacity: 0.6"></div>
                }
                
                <script>
                    getLatest('@nick', '@channel');
                </script>
                if (months.Count > 7)
                {
                    <div id="moremonths" class="scrollspy" >
                        <br/>
                        <h5>More Months</h5>
                        <div class="divider" style="opacity: 0.6"></div>
                        <div class="collection">
                            @for (var i = 8; i < months.Count; i++)
                            {
                                <a href="https://overrustlelogs.net/@channel chatlog/@months[i]/userlogs/@nick.Replace(".txt", string.Empty)" class="collection-item">@months[i]</a>
                            }
                        </div>
                    </div>
                }
            }
        </div>

    </div>
    <div class="col m1 l2 hide-on-med-and-down">
        @*stuff*@
    </div>
</div>